"use client"
// Auto-generated by `npx boneyard-js build` — do not edit
import { registerBones } from 'boneyard-js'
import { configureBoneyard } from 'boneyard-js/react'

import _Header from './Header.bones.json'
import _InventoryTotal from './InventoryTotal.bones.json'
import _ValueByStock from './ValueByStock.bones.json'

configureBoneyard({"color":"#e5e5e5","darkColor":"#2a2a2a","animate":"shimmer","shimmerColor":"#ebebeb","darkShimmerColor":"#333333","speed":"2s","shimmerAngle":110})

registerBones({
  "Header": _Header,
  "InventoryTotal": _InventoryTotal,
  "ValueByStock": _ValueByStock,
})
